### ISSUE TITLE
Doors API change

### ISSUE THREAD

**Issue by heavygale** [Bremaweb/landrush#18]
The mod is no longer compatible with the doors mod included in minetest_game. At in     shared_door.lua is some work to do.

line 19: doors.register_door is deprecated
line 38: attempt to index field 'landrush:shared_door_b_1' (a nil value)

**Comment by heavygale** [comment]
You should merge this commit:
https://github.com/FozLand/landrush/commit/48d4b212c024d6fec256fc53a6bc96033af21e59

And this one propably too:
https://github.com/FozLand/landrush/commit/48d4b212c024d6fec256fc53a6bc96033af21e59

**Comment by Bremaweb** [comment]
The crash is fixed, shared doors work like steel doors for now until I get time to make them allow access to those the area is shared with.

**Comment by Bremaweb** [comment]
This has been completely fixed for a little while now. Shared doors are working like they are supposed to.
