### ISSUE TITLE
Move this mod to "Mod Releases" on forum

### ISSUE THREAD

**Issue by Fixer-007** [Bremaweb/landrush#20]
If this mod is stable enough, you should consider moving it into "Mod Releases" section here https://forum.minetest.net/viewforum.php?f=11. And since it is used for many years on few servers you should consider some final tweaks, fixes, additions and request to move it in "Mod Releases".
More info here:
https://forum.minetest.net/viewtopic.php?f=11&t=1271
https://forum.minetest.net/viewtopic.php?f=11&t=10418
https://forum.minetest.net/viewtopic.php?f=11&t=10029

**Comment by Bremaweb** [comment]
Oh, I thought it was in Mod Releases already. I submitted the request for it to be moved.
